### ISSUE TITLE
$lt, $gt is not working with dates

### ISSUE THREAD

**Issue by ysnfrk** [feathersjs-ecosystem/feathers-nedb#112]
### Steps to reproduce

I wanted to test official example using nedb (as given below) to see whether I can get the logs of the past ten minutes or not. However, it is not working.  I  found same issue in different place so I wanted to open a issue here. The link to comment is given below.  Thanks in advance.

Link:
https://github.com/feathersjs-ecosystem/feathers-reactive/issues/62#issuecomment-469950236

Example:
https://docs.feathersjs.com/api/databases/querying.html#lt-lte
```

// Find all messages older than a day
const DAY_MS = 24 * 60 * 60 * 1000;

app.service('messages').find({
  query: {
    createdAt: {
      $lt: new Date().getTime() - DAY_MS
    }
  }
});

```
### Expected behavior
It should return db records of last day. (If you use example)

### Actual behavior
It returns an empty paginated object as given below.
data:Array(0) []
limit:50
skip:0
total:0

### System configuration
    "@feathersjs/authentication": "^4.5.3",
    "@feathersjs/authentication-local": "^4.5.3",
    "@feathersjs/authentication-oauth": "^4.5.3",
    "@feathersjs/configuration": "^4.5.3",
    "@feathersjs/errors": "^4.5.3",
    "@feathersjs/express": "^4.5.3",
    "@feathersjs/feathers": "^4.5.3",
    "@feathersjs/rest-client": "^4.5.3",
    "@feathersjs/transport-commons": "^4.5.3",
    "compression": "^1.7.4",
    "cors": "^2.8.5",
    "default-gateway": "^6.0.0",
    "feathers-blob": "^2.2.0",
    "feathers-nedb": "^5.1.0",
    "fs-blob-store": "^5.2.1",

**Comment by diegodorado** [comment]
Smae problem here.... seems this repo isnt very active

**Comment by DaddyWarbucks** [comment]
I am not sure there is much `feathers-nedb` can do to solve this problem. If your data/query are coming over REST/Socket then the values are parsed via `qs` or `JSON.parse`, and that is pretty common in Node server land. The values have to get parsed over the wire somehow. And that means dates are turned into datestrings. This is a common problem with basically any Node/Express app that uses the `qs` lib. For example, `?myNumber=1` will be parsed to `{ myNumber: "1" }` (note "1" is a string).

Because NEDB doesn't have models, it doesn't know what type each property is, and can't intelligently convert them like Mongoose may do. So you have to manually convert dates where dates are needed.
